### Name: Abhishek Sahu
### Regs. no: 2241019164
### Section: 07
### Branch: CSE
### Sub: Data Science Workshop-1

#### Q1. Find the index of the 5 th repetition of number 1 in x= np.array ([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2]).

In [1]:
import numpy as np
x=np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
i=np.where(x==1)[0]
if len(i)>=5:
    index=i[4]
print(index)

8


#### Q2. Compute the Euclidean distance between two arrays a = np.array([1,2,3]) b = np.array([4,5,6]).

In [2]:
a=np.array([1,2])
b=np.array([4,7])
distance=np.sqrt(np.sum((b-a)**2))
print(distance)

5.830951894845301


#### Q3.
#### (a) Replace all odd numbers in the array with -1 without changing the array.

In [7]:
x=np.random.randint(1,10,(4,4))
print("Before: ",x)
x[x%2!=0]=-1
print("After: ",x)

Before:  [[8 9 3 2]
 [8 3 3 5]
 [4 5 7 2]
 [8 2 6 2]]
After:  [[ 8 -1 -1  2]
 [ 8 -1 -1 -1]
 [ 4 -1 -1  2]
 [ 8  2  6  2]]


#### (b) From the array a, replace all values greater than 30 to 30 and less than 10 to 10.

In [8]:
x=np.random.randint(1,40,(4,4))
print("Before: ",x)
x[x>30]=30
x[x<10]=10
print("After: ",x)

Before:  [[37 21 33 33]
 [30 12  8 22]
 [38  8  7 32]
 [31 10 28 23]]
After:  [[30 21 30 30]
 [30 12 10 22]
 [30 10 10 30]
 [30 10 28 23]]


#### Q4. Create a 4*4 matrix with entries from uniform distribution data in the interval 10 to 20. Normalize the matrix so that the minimum has a value of 0 and the maximum has a value of 1.


In [6]:
ar=np.random.standard_normal([4,4])
norm=(ar-np.min(ar))/(np.max(ar)-np.min(ar))
print(norm)

[[0.22806511 1.         0.95033576 0.50323795]
 [0.4259267  0.83445958 0.89960937 0.52685037]
 [0.43104312 0.09552581 0.73938069 0.58240617]
 [0.44885941 0.         0.1375678  0.54061639]]


#### Q5. Find the mean, median, and standard deviation of a 1-d array.

In [14]:
import math
ar= np.arange(10) 
print(ar)   
r1 = np.mean(ar) 
print("Mean: ", r1)  
r2 = np.std(ar) 
print("std: ", r2)  
r3 = np.median(ar) 
print("Median: ", math.floor(r3))

[0 1 2 3 4 5 6 7 8 9]
Mean:  4.5
std:  2.8722813232690143
Median:  4


#### Q6. Get all items between 5 and 10 from a. Input: a= [2, 6, 1, 9, 10, 3, 27].

In [5]:
a= np.array([2, 6, 1, 9, 10, 3, 27])
b=a[(a>5) & (a<10)]
print(b)

[6 9]


#### Q7. Convert a 1D array to a 2D array with 2 rows.

In [4]:
import numpy as np
x=np.random.randint(1,5,(10))
print(x)
if len(x)%2==0:
    ar=np.reshape(x,(len(x)//2,2))
    print(ar)

[4 4 2 1 3 1 4 4 2 2]
[[4 4]
 [2 1]
 [3 1]
 [4 4]
 [2 2]]


#### Q8. Create a 2D array and swap the first two rows and two columns.

In [26]:
ar = np.arange(16).reshape(4, 4)
print("Before sharing: ",ar)
ar[[1,0],: ] = ar[[0, 1],: ]
ar[:, [1,0]] = ar[:, [0, 1]]
print("After Swaping",ar)

Before sharing:  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
After Swaping [[ 5  4  6  7]
 [ 1  0  2  3]
 [ 9  8 10 11]
 [13 12 14 15]]


#### Q9. Find the most frequent values in an array of positive integers. The original array is:

In [32]:
ar=np.array([6,9,5,1,7,5,1,0,1,5,5,0,8,9,0,7,0,7,6,5,1,1,9,5,3,8,7,9,6,3,4,5,9,7,2,7,0,2,2,6])
print(ar)
frq=np.bincount(ar).argmax()
print("Most Frequent value: ",frq)

[6 9 5 1 7 5 1 0 1 5 5 0 8 9 0 7 0 7 6 5 1 1 9 5 3 8 7 9 6 3 4 5 9 7 2 7 0
 2 2 6]
Most Frequent value:  5


#### Q10. Create a symmetric matrix of order 4*4, whose items are taken from a standard normal distribution.

In [57]:
x=np.random.standard_normal([4,4])
sym= (x+x.T)/2
print(sym)

[[ 1.43473422 -0.03819647  0.10944884 -0.73992402]
 [-0.03819647  0.42301992  0.37256663 -0.8113106 ]
 [ 0.10944884  0.37256663 -1.18779274  1.23074369]
 [-0.73992402 -0.8113106   1.23074369 -0.5619672 ]]


#### Q11. In a cricket match, a batsman scores any one of {1, 2, 3, 4, 6, 0}. When he scores 0, it will be considered as ”OUT”. If he will face 50 balls maximum, then find the score that he will make before getting ”OUT”. Draw the plot of the run scored by the batsman.

In [13]:
c=0
sum=0
while(c<50):
    x=np.random.choice([0,1,2,3,4,6])
    print(x)
    if(x!=0):
        sum=sum+x
    else:
        print("The user is out")
        break
    c+=1
print("Total run scored: ",sum)

2
0
The user is out
Total run scored:  2


#### Q12. Compute the cross product of two 3*3 matrices.

In [4]:
import numpy as np
arr = np.random.standard_normal([3,3])
arr1 = np.random.standard_normal([3,3])
crs = np.cross(arr, arr1)
print("Cross product of two 3x3 matrices: ")
crs

Cross product of two 3x3 matrices: 


array([[ 4.31598629e+00,  6.30488014e+00,  5.54843176e+00],
       [ 4.06988981e-01, -1.92363572e+00, -1.08024345e+00],
       [ 1.13665348e-01, -3.97226776e-02, -2.30395015e-03]])

#### Q13. Write a NumPy program to sort the student id with increasing height of the students from the given student id and height. Print the integer indices that describe the sort order by multiple columns and the sorted data.

#### Q14. Return array of odd rows and even columns from below numpy array :

In [56]:
x= np.array([[3, 6, 9, 12], [15, 18, 21, 24], [27, 30, 33, 36], [39, 42, 45, 48], [51, 54, 57, 60]])
print(x)
x1=x[::2,1:4:2]
print("Array of odd rows and even columns: ")
print(x1)

[[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]
 [39 42 45 48]
 [51 54 57 60]]
Array of odd rows and even columns: 
[[ 6 12]
 [30 36]
 [54 60]]


#### Q15. Calculate the sum of all rows and columns of a 2-D NumPy array.

In [47]:
ar=np.arange(16).reshape(4,4)
print(ar)
print("Row wise sum: ",np.sum(ar,axis=1))
print("Column wise sum: ",np.sum(ar,axis=0))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Row wise sum:  [ 6 22 38 54]
Column wise sum:  [24 28 32 36]


#### Q16. Write a code to multiply a 5x3 matrix by a 3x2 matrix and create a real matrix product.

In [5]:
x = np.random.random((5,3))
y = np.random.random((3,2))
z = np.dot(x, y)
print("Dot product of two arrays:")
z

Dot product of two arrays:


array([[0.05093981, 0.1558687 ],
       [0.14597006, 0.66842121],
       [0.12952639, 0.43847653],
       [0.13143337, 0.61537858],
       [0.27893568, 0.93115919]])

#### Q17. Write a code to find the roots of the polynomials x 2 − 4x + 7 = 0.

In [6]:
# Enter the coefficients of the poly in the array 
cof = [1, -4, 7] 
print(np.roots(cof))

[2.+1.73205081j 2.-1.73205081j]


#### Q18. Write a code to create a 5x5 array with random values and normalize it row-wise.

In [7]:
nums = np.random.rand(5, 5)
norm_arr = nums / np.linalg.norm(nums, axis=1, keepdims=True)
#This calculates the Euclidean norm of each row in nums.
#The axis=1 argument specifies that the norm should be calculated along the rows,
#and keepdims=True ensures that the result is a column vector with the same number of dimensions as nums.
print("\nNormalize Array row-wise:")
print(norm_arr)


Normalize Array row-wise:
[[0.20446547 0.2755387  0.71998712 0.51680923 0.31112547]
 [0.04475454 0.07797561 0.52991602 0.59526676 0.59729669]
 [0.19092652 0.33253868 0.58244633 0.33211073 0.63515654]
 [0.37720269 0.88639608 0.04442875 0.23808939 0.11558395]
 [0.70238709 0.50474449 0.31414614 0.19944828 0.33677585]]


#### Q19. Write a NumPy program to create a 9*9*2 array with random values and extract any array of shape (5,5,2) from the said array.

In [40]:
ar=np.random.randn(9,9,2)
ar1=ar[:5, :5, :]
print("After extracting an array of (5,5,2): ")
ar1

After extracting an array of (5,5,2): 


array([[[-1.09088812e+00, -1.05367626e+00],
        [ 1.26783054e+00,  1.30778639e+00],
        [ 2.43093905e-04, -1.53278480e+00],
        [-7.42512144e-01, -2.12852884e+00],
        [ 1.78560292e-01,  1.41716680e+00]],

       [[-1.62648137e-01, -8.85494188e-01],
        [ 1.03782447e+00,  9.64226316e-01],
        [ 7.32763604e-02,  1.15776178e-01],
        [ 2.48061143e-01,  8.21023697e-01],
        [-6.36921119e-01,  1.77458458e+00]],

       [[ 1.46589689e+00, -4.81628697e-01],
        [-4.85620580e-01, -1.32115312e-01],
        [-7.95348597e-01, -1.00672736e+00],
        [-4.27841664e-02, -1.03631681e+00],
        [ 1.71130262e+00,  3.94207687e-01]],

       [[ 2.42389004e+00,  1.67817291e+00],
        [ 6.00905383e-01,  5.63711567e-01],
        [ 6.23134656e-01,  1.39701817e+00],
        [ 2.50660523e-01,  3.04255522e-01],
        [-1.24523096e-01, -1.99148996e+00]],

       [[-1.80609277e-01,  2.83245314e-01],
        [ 2.72455246e-01,  3.90885221e-01],
        [-1.05946927e+00

#### Q20. Write a code to create a 4*4 array with random values and sort each column.

In [33]:
ar=np.random.randn(4,4)
print("Before sorting: ",ar)
print("After sorting",np.sort(ar)) 

Before sorting:  [[-1.67300543  0.04009479 -0.1963192   1.25973957]
 [-0.77217869 -0.3440783  -0.23838152 -0.46997477]
 [ 1.02054766 -0.95921059 -0.62573807  1.73734441]
 [ 0.56015483 -0.00583576  1.33241741  0.12307007]]
After sorting [[-1.67300543 -0.1963192   0.04009479  1.25973957]
 [-0.77217869 -0.46997477 -0.3440783  -0.23838152]
 [-0.95921059 -0.62573807  1.02054766  1.73734441]
 [-0.00583576  0.12307007  0.56015483  1.33241741]]
